// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_V_kHhgK31eJw2tzRZt8ipR8DTn0eAuc',
    appId: '1:524236398650:web:b1cd279c612fde2e761503',
    messagingSenderId: '524236398650',
    projectId: 'angular-project-1882',
    authDomain: 'angular-project-1882.firebaseapp.com',
    storageBucket: 'angular-project-1882.firebasestorage.app',
    measurementId: 'G-6T3M3DMLMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1B5T2fmNjQgZrCMvB2WZSULFPs-4DHk',
    appId: '1:524236398650:android:01ed564b89d94f6f761503',
    messagingSenderId: '524236398650',
    projectId: 'angular-project-1882',
    storageBucket: 'angular-project-1882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo74RqkSgu1fkc8Hv8wGSwV3NLPhie8B8',
    appId: '1:524236398650:ios:cd7a3b716a98066f761503',
    messagingSenderId: '524236398650',
    projectId: 'angular-project-1882',
    storageBucket: 'angular-project-1882.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo74RqkSgu1fkc8Hv8wGSwV3NLPhie8B8',
    appId: '1:524236398650:ios:cd7a3b716a98066f761503',
    messagingSenderId: '524236398650',
    projectId: 'angular-project-1882',
    storageBucket: 'angular-project-1882.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_V_kHhgK31eJw2tzRZt8ipR8DTn0eAuc',
    appId: '1:524236398650:web:e1aa55755f3314d7761503',
    messagingSenderId: '524236398650',
    projectId: 'angular-project-1882',
    authDomain: 'angular-project-1882.firebaseapp.com',
    storageBucket: 'angular-project-1882.firebasestorage.app',
    measurementId: 'G-T712TH51KW',
  );
}
